
# Netlify configuration file
[build]
  publish = "dist"
  command = "npm run build"

# Redirect all paths to index.html for single page application routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
